# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/training/Projects/Ultra96v2_wifi_val_2018_2/ultra96v2_valtest_2018_2/hardware/ULTRA96V2/ultra96v2_valtest.srcs/sources_1/bd/ultra96v2_valtest/ip/ultra96v2_valtest_axi_uart16550_0_0/ultra96v2_valtest_axi_uart16550_0_0.xci
# IP: The module: 'ultra96v2_valtest_axi_uart16550_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/training/Projects/Ultra96v2_wifi_val_2018_2/ultra96v2_valtest_2018_2/hardware/ULTRA96V2/ultra96v2_valtest.srcs/sources_1/bd/ultra96v2_valtest/ip/ultra96v2_valtest_axi_uart16550_0_0/ultra96v2_valtest_axi_uart16550_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_valtest_axi_uart16550_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/training/Projects/Ultra96v2_wifi_val_2018_2/ultra96v2_valtest_2018_2/hardware/ULTRA96V2/ultra96v2_valtest.srcs/sources_1/bd/ultra96v2_valtest/ip/ultra96v2_valtest_axi_uart16550_0_0/ultra96v2_valtest_axi_uart16550_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_valtest_axi_uart16550_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/training/Projects/Ultra96v2_wifi_val_2018_2/ultra96v2_valtest_2018_2/hardware/ULTRA96V2/ultra96v2_valtest.srcs/sources_1/bd/ultra96v2_valtest/ip/ultra96v2_valtest_axi_uart16550_0_0/ultra96v2_valtest_axi_uart16550_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_valtest_axi_uart16550_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/training/Projects/Ultra96v2_wifi_val_2018_2/ultra96v2_valtest_2018_2/hardware/ULTRA96V2/ultra96v2_valtest.srcs/sources_1/bd/ultra96v2_valtest/ip/ultra96v2_valtest_axi_uart16550_0_0/ultra96v2_valtest_axi_uart16550_0_0.xci
# IP: The module: 'ultra96v2_valtest_axi_uart16550_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/training/Projects/Ultra96v2_wifi_val_2018_2/ultra96v2_valtest_2018_2/hardware/ULTRA96V2/ultra96v2_valtest.srcs/sources_1/bd/ultra96v2_valtest/ip/ultra96v2_valtest_axi_uart16550_0_0/ultra96v2_valtest_axi_uart16550_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_valtest_axi_uart16550_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/training/Projects/Ultra96v2_wifi_val_2018_2/ultra96v2_valtest_2018_2/hardware/ULTRA96V2/ultra96v2_valtest.srcs/sources_1/bd/ultra96v2_valtest/ip/ultra96v2_valtest_axi_uart16550_0_0/ultra96v2_valtest_axi_uart16550_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_valtest_axi_uart16550_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/training/Projects/Ultra96v2_wifi_val_2018_2/ultra96v2_valtest_2018_2/hardware/ULTRA96V2/ultra96v2_valtest.srcs/sources_1/bd/ultra96v2_valtest/ip/ultra96v2_valtest_axi_uart16550_0_0/ultra96v2_valtest_axi_uart16550_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_valtest_axi_uart16550_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
