# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/2018.2/ultra96v2_valtest.xdc

# Block Designs: bd/ultra96v2_valtest/ultra96v2_valtest.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest || ORIG_REF_NAME==ultra96v2_valtest} -quiet] -quiet

# IP: bd/ultra96v2_valtest/ip/ultra96v2_valtest_zynq_ultra_ps_e_0_0/ultra96v2_valtest_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ultra96v2_valtest_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ultra96v2_valtest/ip/ultra96v2_valtest_axi_uart16550_0_0/ultra96v2_valtest_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest_axi_uart16550_0_0 || ORIG_REF_NAME==ultra96v2_valtest_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/ultra96v2_valtest/ip/ultra96v2_valtest_ps8_0_axi_periph_0/ultra96v2_valtest_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest_ps8_0_axi_periph_0 || ORIG_REF_NAME==ultra96v2_valtest_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/ultra96v2_valtest/ip/ultra96v2_valtest_rst_ps8_0_99M_0/ultra96v2_valtest_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest_rst_ps8_0_99M_0 || ORIG_REF_NAME==ultra96v2_valtest_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/ultra96v2_valtest/ip/ultra96v2_valtest_axi_gpio_0_0/ultra96v2_valtest_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest_axi_gpio_0_0 || ORIG_REF_NAME==ultra96v2_valtest_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ultra96v2_valtest/ip/ultra96v2_valtest_xlconcat_0_0/ultra96v2_valtest_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest_xlconcat_0_0 || ORIG_REF_NAME==ultra96v2_valtest_xlconcat_0_0} -quiet] -quiet

# IP: bd/ultra96v2_valtest/ip/ultra96v2_valtest_xbar_0/ultra96v2_valtest_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest_xbar_0 || ORIG_REF_NAME==ultra96v2_valtest_xbar_0} -quiet] -quiet

# IP: bd/ultra96v2_valtest/ip/ultra96v2_valtest_xlconstant_0_0/ultra96v2_valtest_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest_xlconstant_0_0 || ORIG_REF_NAME==ultra96v2_valtest_xlconstant_0_0} -quiet] -quiet

# IP: bd/ultra96v2_valtest/ip/ultra96v2_valtest_auto_ds_0/ultra96v2_valtest_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest_auto_ds_0 || ORIG_REF_NAME==ultra96v2_valtest_auto_ds_0} -quiet] -quiet

# IP: bd/ultra96v2_valtest/ip/ultra96v2_valtest_auto_pc_0/ultra96v2_valtest_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_valtest_auto_pc_0 || ORIG_REF_NAME==ultra96v2_valtest_auto_pc_0} -quiet] -quiet

# XDC: bd/ultra96v2_valtest/ultra96v2_valtest_ooc.xdc
